### ISSUE TITLE
`pip install rottentomatoes` not working in python 3.4

### ISSUE THREAD

**Issue by djds23** [zachwill/rottentomatoes#8]
I tried this using 2.7 and everything appeared to be working fine, however in python 3.4 I get this error. 

``` python
Downloading/unpacking rottentomatoes
  Downloading rottentomatoes-2.1.tar.gz
  Running setup.py (path:/Users/me/.virutalenvs/myapp/build/rottentomatoes/setup.py) egg_info for package rottentomatoes
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/me/.virutalenvs/myapp/build/rottentomatoes/setup.py", line 8, in <module>
        import rottentomatoes
      File "/Users/me/.virutalenvs/myapp/build/rottentomatoes/rottentomatoes/__init__.py", line 3, in <module>
        from rottentomatoes import RT
    ImportError: cannot import name 'RT'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/me/.virutalenvs/myapp/build/rottentomatoes/setup.py", line 8, in <module>

    import rottentomatoes

  File "/Users/me/.virutalenvs/myapp/build/rottentomatoes/rottentomatoes/__init__.py", line 3, in <module>

    from rottentomatoes import RT

ImportError: cannot import name 'RT'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/me/.virutalenvs/myapp/build/rottentomatoes
Storing debug log for failure in /Users/me/.pip/pip.log
```

any ideas? Thanks for your work on this project.

**Comment by anton44eg** [comment]
I make pull request for this #9

**Comment by drussellmrichie** [comment]
Having the same issue with 3.5.

**Comment by krestenlaust** [comment]
Just use 2.7 😁

**Comment by birdmw** [comment]
I just copied the total contents of rottentomatoes.py into __init__.py and then changed

this:

from urllibimport urlencode

to this:

from urllib.parse import urlencode

in both files. Then the install worked fine.
